"""add token_expires_at to pertemuan

Revision ID: 0fcae14400a0
Revises: 71136ddc2bc3
Create Date: 2026-06-08 13:09:12.221101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fcae14400a0'
down_revision: Union[str, Sequence[str], None] = '71136ddc2bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pertemuan', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pertemuan', 'token_expires_at')
    # ### end Alembic commands ###
