"""add semester_config, jadwal_kelas, update kelas and pertemuan

Revision ID: 71136ddc2bc3
Revises: 89bea614d976
Create Date: 2026-06-08 12:51:53.237243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71136ddc2bc3'
down_revision: Union[str, Sequence[str], None] = '89bea614d976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_semester', sa.String(length=50), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal_kelas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kelas_id', sa.UUID(), nullable=False),
    sa.Column('hari', sa.Enum('SENIN', 'SELASA', 'RABU', 'KAMIS', 'JUMAT', 'SABTU', 'MINGGU', name='harienum'), nullable=False),
    sa.Column('waktu_mulai', sa.Time(), nullable=False),
    sa.Column('waktu_selesai', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('kelas', sa.Column('semester_id', sa.UUID(), nullable=False))
    op.add_column('kelas', sa.Column('deskripsi', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'kelas', 'semester_config', ['semester_id'], ['id'])
    op.drop_column('kelas', 'jadwal')
    op.add_column('pertemuan', sa.Column('tanggal_pertemuan', sa.Date(), nullable=False))
    op.add_column('pertemuan', sa.Column('waktu_mulai_aktual', sa.Time(), nullable=False))
    op.add_column('pertemuan', sa.Column('waktu_selesai_aktual', sa.Time(), nullable=False))
    op.drop_constraint(op.f('pertemuan_token_presensi_key'), 'pertemuan', type_='unique')
    op.drop_column('pertemuan', 'waktu_selesai')
    op.drop_column('pertemuan', 'token_expires_at')
    op.drop_column('pertemuan', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pertemuan', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('pertemuan', sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('pertemuan', sa.Column('waktu_selesai', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('pertemuan_token_presensi_key'), 'pertemuan', ['token_presensi'], postgresql_nulls_not_distinct=False)
    op.drop_column('pertemuan', 'waktu_selesai_aktual')
    op.drop_column('pertemuan', 'waktu_mulai_aktual')
    op.drop_column('pertemuan', 'tanggal_pertemuan')
    op.add_column('kelas', sa.Column('jadwal', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'kelas', type_='foreignkey')
    op.drop_column('kelas', 'deskripsi')
    op.drop_column('kelas', 'semester_id')
    op.drop_table('jadwal_kelas')
    op.drop_table('semester_config')
    # ### end Alembic commands ###
