"""initial schema

Revision ID: 89bea614d976
Revises: 
Create Date: 2026-06-07 17:24:39.147841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bea614d976'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_kelas', sa.String(length=100), nullable=False),
    sa.Column('jadwal', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'GURU', 'SISWA', name='roleenum'), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('kelas_guru',
    sa.Column('kelas_id', sa.UUID(), nullable=False),
    sa.Column('guru_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['guru_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('kelas_id', 'guru_id')
    )
    op.create_table('kelas_siswa',
    sa.Column('kelas_id', sa.UUID(), nullable=False),
    sa.Column('siswa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('kelas_id', 'siswa_id')
    )
    op.create_table('pertemuan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kelas_id', sa.UUID(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('waktu_selesai', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jenis_pertemuan', sa.Enum('ONLINE', 'OFFLINE', name='jenispertemuanenum'), nullable=False),
    sa.Column('token_presensi', sa.String(length=10), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_presensi')
    )
    op.create_table('izin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pertemuan_id', sa.UUID(), nullable=False),
    sa.Column('siswa_id', sa.UUID(), nullable=False),
    sa.Column('alasan', sa.Text(), nullable=False),
    sa.Column('file_bukti', sa.String(length=255), nullable=True),
    sa.Column('status_approval', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='statusapprovalenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pertemuan_id'], ['pertemuan.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kehadiran',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pertemuan_id', sa.UUID(), nullable=False),
    sa.Column('siswa_id', sa.UUID(), nullable=False),
    sa.Column('status_hadir', sa.Enum('HADIR', 'ALPA', 'SAKIT', 'IZIN', name='statushadirenum'), nullable=False),
    sa.Column('metode_presensi', sa.Enum('TOKEN', 'MANUAL', name='metodepresensienum'), nullable=False),
    sa.Column('waktu_presensi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pertemuan_id'], ['pertemuan.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kehadiran')
    op.drop_table('izin')
    op.drop_table('pertemuan')
    op.drop_table('kelas_siswa')
    op.drop_table('kelas_guru')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('kelas')
    # ### end Alembic commands ###
